version: "2"
linters:
  enable:
    - asasalint
    - err113
    - errorlint
    - exhaustive
    - exptostd
    - gocritic
    - govet
    - iface
    - modernize
    - nilnil
    - reassign
    - recvcheck
  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - commentFormatting
        - commentedOutCode
        - unnamedResult
        - exitAfterDefer
        - ifElseChain
